
# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Choreo Dev-Documentation
site_description: Documentation for WSO2 Choreo
site_author: WSO2
site_url: https://wso2.com/choreo/docs/en/

# Repository
repo_name: wso2/docs-choreo-dev
repo_url: https://github.com/wso2/docs-choreo-dev/
edit_uri: https://github.com/wso2/docs-choreo-dev/edit/master/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: WSO2 Choreo - Dev-Documentation

# Configuration
theme:
    name: material
    custom_dir: theme/material
    palette:
        primary: deep-orange
        accent: deep-orange
    logo: images/logo.svg
    favicon: images/favicon.png
    highlightjs: true
    feature:
        tabs: true
    language: 'en'
#Breaks build if there's a warning
strict: true
# Navigation
nav:
    - Documentation: index.md
    - Get Started x:
        - Overview: get-started/overview.md
        - About Choreo: get-started/introduction-to-choreo.md
        - Quick Start Guide: get-started/quick-start-guide.md
        - About this Release: get-started/about-this-release.md
    - Concepts: 
        - Overview: concepts/choreo-concepts.md
    - Tutorials: tutorials/overview.md
    - Videos: videos/videos.md
    - References: references/references.md
    - Community: community/community.md
    - FAQ: faq.md
    - Test: test.md 
    - 1 x:
        - 1.1: get-started/overview.md
        - 1.2: get-started/introduction-to-choreo.md
        - 1.3: get-started/quick-start-guide.md
        - 1.4: get-started/about-this-release.md       
# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          linenums: true
          use_pygments: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
          permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets:
          base_path: docs
plugins:
    - search
    - markdownextradata: {}
    # Extra
extra_css:
    - assets/lib/highlightjs/default.min.css
    - assets/css/theme.css
    - assets/lib/json-formatter/json-formatter.css
extra_javascript:
    - assets/lib/json-formatter/json-formatter.umd.js
    - assets/lib/highlightjs/highlight.min.js
    - assets/js/theme.js
    - assets/lib/backtotop/js/util.js
    - assets/lib/backtotop/js/main.js
extra:
    social:
        - type: github
          link: https://github.com/wso2
        - type: twitter
          link: https://twitter.com/wso2
        - type: linkedin
          link: https://www.linkedin.com/company/wso2
    site_version: 1.0.0
    #base_path: http://localhost:8000
    base_path: http://localhost:8000
