trigger:
  batch: true
  branches:
    include:
    - dev

pr: none

jobs:
- job: GenerateDevDocSite

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo "Starting doc site build"
      python3 --version
      pip3 --version
